### ISSUE TITLE
apex ("bare") domain goes to a parked page

### ISSUE THREAD

**Issue by joeyschoblaska** [CoralineAda/opensourceforwomen.org#10]
Not a code issue per se, but [os4w.org](http://os4w.org/) appears to go to a parked page hosted by the domain registrar. It should probably redirect to [www.os4w.org](http://www.os4w.org/) (or vice versa), or render the same content.

![image](https://cloud.githubusercontent.com/assets/29129/9724697/833e91d8-55a1-11e5-825a-3bf8b91dc911.png)

**Comment by CoralineAda** [comment]
I’m working on this… DNS is a mystery to me.

**Comment by CoralineAda** [comment]
Fixed! Thanks for pointing this out.
