### ISSUE TITLE
Allow users to upload avatars

### ISSUE THREAD

**Issue by CoralineAda** [CoralineAda/opensourceforwomen.org#24]
Fall back to gravatars if no avatar is present.

**Comment by CoralineAda** [comment]
In progress now

**Comment by jellene4eva** [comment]
I know you're working on this already, but can I still try a hand at the issue?

**Comment by jellene4eva** [comment]
I couldn't figure out how to let users delete the avatar attachment though. my `link_to` paths kept giving me an error...
