### ISSUE TITLE
Consider creating a CONTRIBUTING file or TEMPLATES for ISSUES and PRs

### ISSUE THREAD

**Issue by FlaviaFortes** [CoralineAda/opensourceforwomen.org#43]
Those files would help a lot people who wants to contribute to the project. :)

**Comment by CoralineAda** [comment]
That’s a great idea. Do you have any interest in drafting such a document?

**Comment by FlaviaFortes** [comment]
Sure!

**Comment by CoralineAda** [comment]
Awesome! Feel free to pass drafts along for review as you go, if you’d like ongoing feedback.

**Comment by FlaviaFortes** [comment]
I have a PR ready with the following changes on README:

```md
## Contributing
Everyone is welcome to contribute to the project by creating issues or sending pull requests.
If you plan on sending a pull request, take a look at the following github articles:

- [Working with forks](https://help.github.com/articles/working-with-forks/)
- [Using pull requests](https://help.github.com/articles/using-pull-requests)
```


What do you think? Is this info worth keeping on README?

**Comment by CoralineAda** [comment]
Can I see it?

**Comment by FlaviaFortes** [comment]
Here: https://github.com/CoralineAda/opensourceforwomen.org/pull/44/files
