### ISSUE TITLE
Unclear what this is about

### ISSUE THREAD

**Issue by selfthinker** [CoralineAda/opensourceforwomen.org#6]
I don't understand what this project is about.
The (single page) website is very confusing. "Together we can make this happen." Together we can make **what** happen? It's supposed to be "a resource for connecting all women [...] to open source projects", but there is **not a single resource**.

Is this a case of an unfinished project? Or is this only a teaser to search for collaborators? If yes, it is missing that vital bit of information and it should at least give some examples of what could potentially be part of this project and what the overall plan is.

**Comment by CoralineAda** [comment]
The only thing you can do today is sign up to show interest / receive notifications. The site is under development now.

**Comment by selfthinker** [comment]
This doesn't really answer the question. (Show interest in what? Receive notifications for what?)
Does that mean you don't know yet what this project will be about or you don't want to share that bit of information? The former would be fine (but it would help managing expectations if it was stated somewhere), the latter would go a bit against the collaborative aspect of Open Source.

**Comment by CoralineAda** [comment]
I’m collaborating with a few women to build the site out right now. Progress is being made! The signup is basically to gauge interest in the creation of a resource for connecting women to open source. The site will feature pairing and mentoring opportunities and list projects that are open, welcoming, and safe for women to contribute to. It will be open to contributions once the beta goes live, hopefully in the next couple of months.

Does that answer your question?

**Comment by selfthinker** [comment]
Thanks. Yes, that answers my question.
Ideally this information could be incorporated into the website as it would help others who have the same question.
